apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: discord-webhook
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: lab-iac/flux/discord-webhook
        property: url
