---
galaxy_info:
  author: bearf
  description: Create and configure ZFS raidz1 pool on R730xd
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
