---
- name: Export nfs
  ansible.builtin.command: exportfs -ra

- name: Restart nfs-server
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted
    daemon_reload: true

- name: Restart nfs-idmapd
  ansible.builtin.systemd:
    name: nfs-idmapd
    state: restarted
