apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello-cluster
  namespace: flux-system
spec:
  interval: 5m
  releaseName: hello-cluster
  targetNamespace: hello-cluster
  chart:
    spec:
      chart: ./deploy
      sourceRef:
        kind: GitRepository
        name: hello-cluster
        namespace: flux-system
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
